**1. Initialization**

In [7]:
from __future__ import absolute_import, division, print_function, unicode_literals
!pip install -q tensorflow==2.0.0-beta1
!pip install "numpy<1.17"

import numpy as np
import tensorflow as tf

print("TF", tf.__version__)
print("NP", np.__version__)


TF 2.0.0-beta1
NP 1.18.3


**2. Tensor manipulation**

In [2]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8] ,[9, 10, 11, 12]],
                   [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])

print("Shape of complex tf.constant")
print("---------------------------")

print(t)

print("Rank of complex tf.constant")
print("-------------------")
print(t.numpy().ndim)


Shape of complex tf.constant
---------------------------
tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)
Rank of complex tf.constant
-------------------
4


In [3]:
tf_matrix1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tf_matrix2 = tf.constant([[1], [2]], dtype=tf.float32)
print("Shape of tf.constant")
print("--------------------")
print(tf.shape(tf_matrix1))
print(tf.shape(tf_matrix2))

print("Convert from tf.constant to numpy")
print("--------------------------------")
print(tf_matrix1.numpy())
print(tf_matrix2.numpy())
print("Rank of tf.constant")
print("-------------------")
print(tf_matrix1.numpy().ndim)
print(tf_matrix2.numpy().ndim)

print("Use tf.linalg.matmul")
print("--------------------")
print(tf.linalg.matmul(tf_matrix1, tf_matrix2))

print("Use multiply(*, broadcasting)")
print("--------------------")
print(tf_matrix1 * tf_matrix2)

Shape of tf.constant
--------------------
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor([2 1], shape=(2,), dtype=int32)
Convert from tf.constant to numpy
--------------------------------
[[1. 2.]
 [3. 4.]]
[[1.]
 [2.]]
Rank of tf.constant
-------------------
2
2
Use tf.linalg.matmul
--------------------
tf.Tensor(
[[ 5.]
 [11.]], shape=(2, 1), dtype=float32)
Use multiply(*, broadcasting)
--------------------
tf.Tensor(
[[1. 2.]
 [6. 8.]], shape=(2, 2), dtype=float32)


In [4]:
print(tf.reduce_mean([1., 2.], axis=0))

print("Use math.reduce_mean with differ axis")
print("------------------------------------")
print(tf.reduce_mean(tf_matrix1, axis=0))
print(tf.reduce_mean(tf_matrix1, axis=1))

print("Use math.reduce_sum with differ axis")
print("------------------------------------")
print(tf.reduce_sum(tf_matrix1, axis=0))
print(tf.reduce_sum(tf_matrix1, axis=-1))

print("Get matrix mean use reduce_sum and reduce_mean")
print("----------------------------------------------")
print(tf.reduce_mean(tf.reduce_sum(tf_matrix1, axis=-1)))

tf.Tensor(1.5, shape=(), dtype=float32)
Use math.reduce_mean with differ axis
------------------------------------
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
Use math.reduce_sum with differ axis
------------------------------------
tf.Tensor([4. 6.], shape=(2,), dtype=float32)
tf.Tensor([3. 7.], shape=(2,), dtype=float32)
Get matrix mean use reduce_sum and reduce_mean
----------------------------------------------
tf.Tensor(5.0, shape=(), dtype=float32)


In [5]:
tf_matrix3=tf.constant([[1, 2, 4], 
                        [2, 0, 1]])
print("Use math.argmax with differ axis")
print("-------------------------------")
print(tf.math.argmax(tf_matrix3, axis=0))
print(tf.math.argmax(tf_matrix3, axis=1))
print(tf.math.argmax(tf_matrix3, axis=-1))

Use math.argmax with differ axis
-------------------------------
tf.Tensor([1 0 0], shape=(3,), dtype=int64)
tf.Tensor([2 0], shape=(2,), dtype=int64)
tf.Tensor([2 0], shape=(2,), dtype=int64)


In [21]:
tf_matrix4=tf.constant([[[0, 1, 2], 
                         [3, 4, 5]],
                        [[6, 7, 8],
                         [9, 10, 11]]])
print(tf_matrix4)
print("Use reshape")
print("-------------------------------")
print(tf.reshape(tf_matrix4, shape=[-1, 3])) # -1 : unneccesary
print(tf.reshape(tf_matrix4, shape=[-1, 1, 3])) # -1 : unneccesary

print("Use squeeze to [[0], [1], [2]")
print("------------------------------")
print(tf.squeeze([[0], [1], [2]]))
print("Use expand_dims to [0, 1, 2]")
print("------------------------------")
print(tf.constant([0, 1, 2]))
print(tf.expand_dims([0, 1, 2], 0))
print(tf.expand_dims([0, 1, 2], 1))

tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]], shape=(2, 2, 3), dtype=int32)
Use reshape
-------------------------------
tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]], shape=(4, 1, 3), dtype=int32)
Use squeeze to [[0], [1], [2]
------------------------------
tf.Tensor([0 1 2], shape=(3,), dtype=int32)
Use expand_dims to [0, 1, 2]
------------------------------
tf.Tensor([0 1 2], shape=(3,), dtype=int32)
tf.Tensor([[0 1 2]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)


In [23]:
print("Use onehot to [[0], [1], [2], [0]]")
print("----------------------------------")
print(tf.one_hot([[0], [1], [2], [0]], depth=3))
print("Delete one axis")
onehot = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(onehot, shape=[-1, 3])

Use onehot to [[0], [1], [2], [0]]
------------------------------
tf.Tensor(
[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]], shape=(4, 1, 3), dtype=float32)
Delete one axis


<tf.Tensor: id=269, shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)>

In [31]:
print("Use cast")
print("--------")
print(tf.cast([1.8, 2.2, 3.3, 4.9], dtype=tf.int32))
print(tf.cast([True, False, 1 == 1, 0 == 1], dtype=tf.int32))

Use cast
------------------------------
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)


In [36]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

print("Use stack")
print("---------")
print(tf.stack([x, y, z]))
print(tf.stack([x, y, z], axis = 1))

Use stack
------------------------------
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [37]:
print("Use ones and zeros like")
print("-----------------------")
print(tf.ones_like(tf_matrix1))
print(tf.zeros_like(tf_matrix1))

Use ones and zeros like
------------------------------
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [38]:
print("Use zip")
print("-------")
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

Use zip
-------
1 4
2 5
3 6
